"""Initial migration

Revision ID: 176d28ecf37a
Revises: 7e53381e8889
Create Date: 2024-12-16 03:01:58.480898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176d28ecf37a'
down_revision = '7e53381e8889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
