"""Upgrade migration

Revision ID: 689986c0af14
Revises: 176d28ecf37a
Create Date: 2024-12-16 14:08:05.153886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689986c0af14'
down_revision = '176d28ecf37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=70), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
