"""empty message

Revision ID: 7d0324860550
Revises: 
Create Date: 2024-10-17 18:14:23.013642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection



# revision identifiers, used by Alembic.
revision = '7d0324860550'
down_revision = None
branch_labels = None
depends_on = None

# op.add_column('user', sa.Column('is_confirmed', sa.Boolean(), nullable=False, server_default='0'))
bind = op.get_bind()
insp = reflection.Inspector.from_engine(bind)
if 'is_confirmed' not in [column['name'] for column in insp.get_columns('user')]:
    op.add_column('user', sa.Column('is_confirmed', sa.Boolean(), nullable=False, server_default='0'))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'partner_media', ['logo_image_id'], ['media_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'media', ['logo_image_id'], ['media_id'])

    # ### end Alembic commands ###
